### Test Unbprotected
GET http://localhost:3001/hello HTTP/1.1
Content-Type: application/json
Authorization: Bearer xxx

{
    "email": "test4@test.com",
    "password": "P@ssword1"
}

### Test Protected

POST http://localhost:3001/protected HTTP/1.1
Content-Type: application/json
Authorization: Bearer xxx

{
    "email": "test4@test.com",
    "password": "P@ssword1"
}